import {
    PiGraduationCap, PiHandCoins, PiUsers, PiBriefcase, PiDotsThree,
    PiHouse, PiLightningFill, PiBank, PiPiggyBank,
    PiDeviceMobile, PiArrowsClockwise, PiAirplaneTilt, PiGift, PiLaptop,
    PiTrain, PiKey, PiShieldCheck, PiHeart, PiBuildings, PiReceipt,
    PiTarget, PiHandHeart,
} from 'react-icons/pi'

/* ──────────── INCOME CATEGORIES ──────────── */

export const INCOME_CATEGORIES = [
    {
        id: 'student_finance',
        label: 'Student Finance',
        subtitle: 'Maintenance loans or grants (usually paid in three big chunks).',
        Icon: PiGraduationCap,
        color: '#147b75',
        defaultFrequency: 'irregular',
        frequencyOptions: ['yearly', 'irregular'],
        frequencyLabels: { yearly: 'Per year', irregular: 'Per instalment' },
        entryLabel: 'Payment',
        addLabel: 'Add another payment',
        defaultMonths: ['october', 'january', 'april'],
        defaultDates: {},
        panelId: 'studentFinance',
        formKey: 'studentFinanceEntries',
    },
    {
        id: 'bursary',
        label: 'Bursary',
        subtitle: 'Extra grants or "free" money from the uni.',
        Icon: PiHandCoins,
        color: '#1a9e97',
        defaultFrequency: 'irregular',
        frequencyOptions: ['yearly', 'irregular'],
        frequencyLabels: { yearly: 'Per year', irregular: 'Per instalment' },
        entryLabel: 'Bursary',
        addLabel: 'Add another bursary',
        defaultMonths: ['october', 'february', 'march'],
        defaultDates: { october: '2025-10-27', february: '2026-02-09', march: '2026-03-30' },
        panelId: 'bursary',
        formKey: 'bursaryEntries',
    },
    {
        id: 'job',
        label: 'Job',
        subtitle: 'Wages from part-time work, shifts, or "gig" roles.',
        Icon: PiBriefcase,
        color: '#5a7c4f',
        defaultFrequency: 'monthly',
        frequencyOptions: ['weekly', 'fortnightly', 'monthly', 'yearly', 'irregular', 'one-off'],
        entryLabel: 'Job',
        addLabel: 'Add another job',
        defaultMonths: [],
        defaultDates: {},
        panelId: 'job',
        formKey: 'jobEntries',
    },
    {
        id: 'family_support',
        label: 'Family Support',
        subtitle: 'Regular help or one-off gifts from family.',
        Icon: PiUsers,
        color: '#3b82a0',
        defaultFrequency: 'monthly',
        frequencyOptions: ['weekly', 'fortnightly', 'monthly', 'yearly', 'irregular', 'one-off'],
        entryLabel: 'Payment',
        addLabel: 'Add another payment',
        defaultMonths: [],
        defaultDates: {},
        panelId: 'familySupport',
        formKey: 'familySupportEntries',
    },
    {
        id: 'savings_income',
        label: 'Savings',
        subtitle: 'Money moved over from a separate savings pot.',
        Icon: PiPiggyBank,
        color: '#1a9e97',
        defaultFrequency: 'monthly',
        frequencyOptions: ['weekly', 'fortnightly', 'monthly', 'yearly', 'irregular', 'one-off'],
        entryLabel: 'Transfer',
        addLabel: 'Add another transfer',
        defaultMonths: [],
        defaultDates: {},
        panelId: 'savingsIncome',
        formKey: 'savingsIncomeEntries',
    },
    {
        id: 'side_hustles',
        label: 'Side Hustle',
        subtitle: 'Selling clothes online, tutoring, or freelance projects.',
        Icon: PiLaptop,
        color: '#6366f1',
        defaultFrequency: 'monthly',
        frequencyOptions: ['weekly', 'fortnightly', 'monthly', 'yearly', 'irregular', 'one-off'],
        entryLabel: 'Hustle',
        addLabel: 'Add another hustle',
        defaultMonths: [],
        defaultDates: {},
        panelId: 'sideHustles',
        formKey: 'sideHustlesEntries',
    },
    {
        id: 'benefits',
        label: 'Benefits',
        subtitle: 'Universal Credit, PIP, or Child Benefit.',
        Icon: PiHandHeart,
        color: '#147b75',
        defaultFrequency: 'monthly',
        frequencyOptions: ['weekly', 'fortnightly', 'monthly', 'yearly', 'irregular', 'one-off'],
        entryLabel: 'Benefit',
        addLabel: 'Add another benefit',
        defaultMonths: [],
        defaultDates: {},
        panelId: 'benefits',
        formKey: 'benefitsEntries',
    },
    {
        id: 'other_income',
        label: 'Other',
        subtitle: 'Any other income you want to add!',
        Icon: PiDotsThree,
        color: '#888',
        defaultFrequency: 'one-off',
        frequencyOptions: ['weekly', 'fortnightly', 'monthly', 'yearly', 'irregular', 'one-off'],
        entryLabel: 'Income',
        addLabel: 'Add another income',
        defaultMonths: [],
        defaultDates: {},
        panelId: 'otherIncome',
        formKey: 'otherIncomeEntries',
        nameEditable: true,
    },
]

/* ──────────── EXPENSE CATEGORIES ──────────── */

export const EXPENSE_CATEGORIES = [
    {
        id: 'uni_fees',
        label: 'University Fees',
        subtitle: 'Only put these down if the money comes out of your bank account.',
        Icon: PiBank,
        color: '#c0392b',
        defaultFrequency: 'irregular',
        frequencyOptions: ['weekly', 'fortnightly', 'monthly', 'yearly', 'irregular', 'one-off'],
        entryLabel: 'Fee',
        addLabel: 'Add another fee',
        defaultMonths: [],
        defaultDates: {},
        panelId: 'uniFees',
        formKey: 'uniFeesEntries',
    },
    {
        id: 'rent',
        label: 'Rent & Mortgage',
        subtitle: 'Halls, private landlords, or home payments.',
        Icon: PiHouse,
        color: '#e06470',
        defaultFrequency: 'monthly',
        frequencyOptions: ['weekly', 'fortnightly', 'monthly', 'yearly', 'irregular', 'one-off'],
        entryLabel: 'Payment',
        addLabel: 'Add another payment',
        defaultMonths: [],
        defaultDates: {},
        panelId: 'rent',
        formKey: 'rentEntries',
    },
    {
        id: 'bills',
        label: 'Bills',
        subtitle: 'Gas, electric, water, and Wi-Fi!',
        Icon: PiLightningFill,
        color: '#e8838e',
        defaultFrequency: 'monthly',
        frequencyOptions: ['weekly', 'fortnightly', 'monthly', 'yearly', 'irregular', 'one-off'],
        entryLabel: 'Bill',
        addLabel: 'Add another bill',
        defaultMonths: [],
        defaultDates: {},
        panelId: 'bills',
        formKey: 'billsEntries',
    },
    {
        id: 'phone_subscriptions',
        label: 'Subscriptions',
        subtitle: 'Spotify, Netflix, the gym, or your phone contract.',
        Icon: PiArrowsClockwise,
        color: '#8b5cf6',
        defaultFrequency: 'monthly',
        frequencyOptions: ['weekly', 'fortnightly', 'monthly', 'yearly', 'irregular', 'one-off'],
        entryLabel: 'Subscription',
        addLabel: 'Add another subscription',
        defaultMonths: [],
        defaultDates: {},
        panelId: 'phoneSubscriptions',
        formKey: 'phoneSubscriptionsEntries',
    },
    {
        id: 'holiday_trips',
        label: 'Holiday & Trips',
        subtitle: 'Estimate how much you plan to spend on any upcoming trips.',
        Icon: PiAirplaneTilt,
        color: '#e06470',
        defaultFrequency: 'one-off',
        frequencyOptions: ['weekly', 'fortnightly', 'monthly', 'yearly', 'irregular', 'one-off'],
        entryLabel: 'Trip',
        addLabel: 'Add another trip',
        defaultMonths: [],
        defaultDates: {},
        panelId: 'holidayTrips',
        formKey: 'holidayTripsEntries',
    },
    {
        id: 'savings_goals',
        label: 'Savings Goals',
        subtitle: "Enter how much money you'd like to put into savings.",
        Icon: PiTarget,
        color: '#d4566a',
        defaultFrequency: 'monthly',
        frequencyOptions: ['weekly', 'fortnightly', 'monthly', 'yearly', 'irregular', 'one-off'],
        entryLabel: 'Saving',
        addLabel: 'Add another goal',
        defaultMonths: [],
        defaultDates: {},
        panelId: 'savingsGoals',
        formKey: 'savingsGoalsEntries',
    },
    {
        id: 'predictable_travel',
        label: 'Predictable Travel',
        subtitle: "Any travel costs that you know exactly how much you'll pay for.",
        Icon: PiTrain,
        color: '#cf5c68',
        defaultFrequency: 'one-off',
        frequencyOptions: ['weekly', 'fortnightly', 'monthly', 'yearly', 'irregular', 'one-off'],
        entryLabel: 'Travel cost',
        addLabel: 'Add another cost',
        defaultMonths: [],
        defaultDates: {},
        panelId: 'predictableTravel',
        formKey: 'predictableTravelEntries',
    },
    {
        id: 'big_gifts',
        label: 'Big Gifts',
        subtitle: "If you know when and how much it'll cost, enter it here.",
        Icon: PiGift,
        color: '#e8838e',
        defaultFrequency: 'one-off',
        frequencyOptions: ['weekly', 'fortnightly', 'monthly', 'yearly', 'irregular', 'one-off'],
        entryLabel: 'Gift',
        addLabel: 'Add another gift',
        defaultMonths: [],
        defaultDates: {},
        panelId: 'bigGifts',
        formKey: 'bigGiftsEntries',
    },
    {
        id: 'rental_deposit',
        label: 'Rental Deposit',
        subtitle: "You'll get this back but you need to be aware of it going out!",
        Icon: PiKey,
        color: '#e06470',
        defaultFrequency: 'one-off',
        frequencyOptions: ['weekly', 'fortnightly', 'monthly', 'yearly', 'irregular', 'one-off'],
        entryLabel: 'Deposit',
        addLabel: 'Add another deposit',
        defaultMonths: [],
        defaultDates: {},
        panelId: 'rentalDeposit',
        formKey: 'rentalDepositEntries',
    },
    {
        id: 'insurance',
        label: 'Insurance',
        subtitle: 'Protecting your laptop, bike, or car.',
        Icon: PiShieldCheck,
        color: '#cf5c68',
        defaultFrequency: 'monthly',
        frequencyOptions: ['weekly', 'fortnightly', 'monthly', 'yearly', 'irregular', 'one-off'],
        entryLabel: 'Policy',
        addLabel: 'Add another policy',
        defaultMonths: [],
        defaultDates: {},
        panelId: 'insurance',
        formKey: 'insuranceEntries',
    },
    {
        id: 'sending_money_home',
        label: 'Sending Money Home',
        subtitle: 'Enter any money that you send back to support family.',
        Icon: PiHeart,
        color: '#d4566a',
        defaultFrequency: 'monthly',
        frequencyOptions: ['weekly', 'fortnightly', 'monthly', 'yearly', 'irregular', 'one-off'],
        entryLabel: 'Transfer',
        addLabel: 'Add another transfer',
        defaultMonths: [],
        defaultDates: {},
        panelId: 'sendingMoneyHome',
        formKey: 'sendingMoneyHomeEntries',
    },
    {
        id: 'council_tax',
        label: 'Council Tax',
        subtitle: '(Only if you\'re living with non-students).',
        Icon: PiBuildings,
        color: '#c0392b',
        defaultFrequency: 'monthly',
        frequencyOptions: ['weekly', 'fortnightly', 'monthly', 'yearly', 'irregular', 'one-off'],
        entryLabel: 'Payment',
        addLabel: 'Add another payment',
        defaultMonths: [],
        defaultDates: {},
        panelId: 'councilTax',
        formKey: 'councilTaxEntries',
    },
    {
        id: 'loan_repayment',
        label: 'Loan Repayment',
        subtitle: "Money you're paying back on any debt.",
        Icon: PiReceipt,
        color: '#e06470',
        defaultFrequency: 'monthly',
        frequencyOptions: ['weekly', 'fortnightly', 'monthly', 'yearly', 'irregular', 'one-off'],
        entryLabel: 'Repayment',
        addLabel: 'Add another repayment',
        defaultMonths: [],
        defaultDates: {},
        panelId: 'loanRepayment',
        formKey: 'loanRepaymentEntries',
    },
    {
        id: 'graduation',
        label: 'Graduation',
        subtitle: 'Gown hire and graduation tickets (final year!)',
        Icon: PiGraduationCap,
        color: '#d4566a',
        defaultFrequency: 'one-off',
        frequencyOptions: ['weekly', 'fortnightly', 'monthly', 'yearly', 'irregular', 'one-off'],
        entryLabel: 'Cost',
        addLabel: 'Add another cost',
        defaultMonths: [],
        defaultDates: {},
        panelId: 'graduation',
        formKey: 'graduationEntries',
    },
    {
        id: 'other_expense',
        label: 'Other',
        subtitle: 'Any other expenses you want to add!',
        Icon: PiDotsThree,
        color: '#888',
        defaultFrequency: 'one-off',
        frequencyOptions: ['weekly', 'fortnightly', 'monthly', 'yearly', 'irregular', 'one-off'],
        entryLabel: 'Expense',
        addLabel: 'Add another expense',
        defaultMonths: [],
        defaultDates: {},
        panelId: 'otherExpense',
        formKey: 'otherExpenseEntries',
        nameEditable: true,
    },
]

/* ──────────── COMBINED LOOKUPS ──────────── */

export const ALL_CATEGORIES = [...INCOME_CATEGORIES, ...EXPENSE_CATEGORIES]
export const CATEGORY_MAP = Object.fromEntries(ALL_CATEGORIES.map(c => [c.id, c]))

/* Icon + color lookup (for SOURCE_ICONS in Dashboard) */
export const SOURCE_ICONS = Object.fromEntries(
    ALL_CATEGORIES.map(c => [c.id, { Icon: c.Icon, color: c.color }])
)
